keys:
  - &fword age1n9e7ymdmcprdynwutygfvd6an2h9xcvpneehu9gcsd93vr0mvg5sqndy08
  - &yesmachine age1rs4fcwsjt7v0uja0v4a9aedrakmvl67sk69yjhzdsrusl3a29glsq40m5e
  - &helmut age1vksq4426jdzk5reu3889e283lvvew66pqwea9s29q802kycp63vsfve5th
creation_rules:
  - path_regex: hosts/secrets/.*
    key_groups:
      - age:
          - *fword
          - *yesmachine
          - *helmut
