keys:
  - &fword age1n9e7ymdmcprdynwutygfvd6an2h9xcvpneehu9gcsd93vr0mvg5sqndy08
  - &yesmachine age1rs4fcwsjt7v0uja0v4a9aedrakmvl67sk69yjhzdsrusl3a29glsq40m5e
creation_rules:
  - path_regex: host/secrets/.*
    key_groups:
      - age:
          - *fword
          - *yesmachine
