#!/bin/bash
CONFIGDIR="$HOME/.config/bspwm/"

# CONFIG
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         2
bspc config window_gap           3
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       none
bspc config ignore_ewmh_focus    true
bspc config external_rules_command $CONFIGDIR/bspwm-rules.lua

# RULES
bspc rule -a librewolf desktop='II' follow='off'

source $CONFIGDIR/bspwmrc-local
