# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1645e1e9-e69b-4169-8837-53d4ef8a89ed";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-8cbeb85f-d04d-49be-a5b2-9f23d873dc25".device = "/dev/disk/by-uuid/8cbeb85f-d04d-49be-a5b2-9f23d873dc25";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5783-29FA";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" "defaults"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/dbea0cfb-3304-44cf-ab1f-c707cf413691";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp170s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
