[helpers]

[shell]
depends = ["gitconfig", "fish"]

[shell.files]
".tmux.conf" = { target = "~/.tmux.conf", type = "symbolic" }
nvim = { target = "~/.config/nvim", type = "symbolic" }
neomutt = { target = "~/.config/neomutt", type = "symbolic", if = '(is_executable "neomutt")' }
"starship.toml" = { target = "~/.config/starship.toml", type = "symbolic", if = '(is_executable "starship")' }
"khal.toml" = { target = "~/.config/khal/config", type = "symbolic", if = '(is_executable "khal")' }

[graphical.files]
"kitty.conf" = { target = "~/.config/kitty/kitty.conf", type = "template", if = '(eq apps.terminal "kitty")' }
"leftwm.config.toml" = { target = "~/.config/leftwm/config.toml", type = "template", if = '(eq wm.name "leftwm")' }
"sxhkdrc.bspwm" = { target = "~/.config/sxhkd/sxhkdrc", type = "template", if = '(eq wm.name "bspwm")' }
"picom.conf" = { target = "~/.config/picom.conf", type = "symbolic", if = '(is_executable "picom")'}

[graphical.variables.apps]
terminal = "kitty"
terminal_args = ""
font = "Noto Sans Mono SemiCondensed Medium"
font_size = "10"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"
"fish/functions" = "~/.config/fish/functions"

[zsh.files]
".zshenv" = "~/.zshenv"
"zsh/zshrc" = "~/.config/zsh/.zshrc"
"zsh/zplugins" = "~/.config/zsh/zplugins"
"zsh/zalias" = "~/.config/zsh/zalias"

[gitconfig.files]
".gitconfig" = "~/.gitconfig"

[gitconfig.variables.git]
username = "0x5a4"
email = "54070204+0x5a4@users.noreply.github.com"
doCommitSigning = false
gpgkey = "None" 
