[shell]
depends = ["fish"]

[shell.files]
nvim = { target = "~/.config/nvim", type = "symbolic" }
tmux = "~/.config/tmux"
bashrc = "~/.bashrc"
"starship.toml" = { target = "~/.config/starship.toml", type = "symbolic", if = '(is_executable "starship")' }

[org.files]
neomutt = { target = "~/.config/neomutt", type = "symbolic", if = '(is_executable "neomutt")' }
"khal.toml" = { target = "~/.config/khal/config", type = "symbolic", if = '(is_executable "khal")' }

[X.files]
# Window Manager Config
"leftwm.toml" = { target = "~/.config/leftwm/config.toml", type = "template", if = '(eq wm.name "leftwm")' }
"sxhkdrc.bspwm" = { target = "~/.config/sxhkd/sxhkdrc", type = "template", if = '(eq wm.name "bspwm")' }
"bspwm-rules.lua" = { target = "~/.config/bspwm/bspwm-rules.lua", type = "template", if = '(eq wm.name "bspwm")' }
# Other
"kitty.conf" = { target = "~/.config/kitty/kitty.conf", type = "template", if = '(eq apps.terminal "kitty")' }
"picom.conf" = { target = "~/.config/picom.conf", type = "symbolic", if = '(is_executable "picom")'}
zathurarc = "~/.config/zathura/zathurarc"
ideavimrc = "~/.ideavimrc"

[X.variables.apps]
terminal = "kitty"
terminal_args = ""
font = "Noto Sans Mono SemiCondensed Medium"
font_size = "10"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"
"fish/functions" = "~/.config/fish/functions"
"fish/conf.d" = "~/.config/fish/conf.d"

[zsh.files]
"zshenv" = "~/.zshenv"
"zsh/zshrc" = "~/.config/zsh/.zshrc"
"zsh/zplugins" = "~/.config/zsh/zplugins"
"zsh/zalias" = "~/.config/zsh/zalias"

[git.files]
gitconfig = "~/.gitconfig"

[git.variables.git]
username = "0x5a4"
email = "54070204+0x5a4@users.noreply.github.com"
