# Packages
[all]
depends = ["shell", "org", "X", "wayland"]

[shell]
depends = ["fish", "neovim", "tmux", "bash", "starship", "git"]

[org]
depends = ["neomutt", "khal"]

[X]
depends = ["bspwm", "kitty", "zathura", "picom"]

[wayland]
depends = ["hyprland", "kitty", "zathura"]

# Files
[neovim.files]
nvim = { target = "~/.config/nvim", type = "symbolic" }

[tmux.files]
tmux = "~/.config/tmux"

[bash.files]
bashrc = "~/.bashrc"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[neomutt.files]
neomutt = { target = "~/.config/neomutt", type = "symbolic" }

[khal.files]
"khal.toml" = "~/.config/khal/config"

[kitty.files]
"kitty.conf" = "~/.config/kitty/kitty.conf"

[bspwm.files]
"bspwm-rules.lua" = { target = "~/.config/bspwm/bspwm-rules.lua", type = "template" }
"sxhkdrc.bspwm" = { target = "~/.config/sxhkd/sxhkdrc", type = "template" }

[zathura.files]
zathurarc = "~/.config/zathura/zathurarc"

[picom.files]
"picom.conf" = "~/.config/picom.conf"

[idea.files]
ideavimrc = "~/.ideavimrc"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"
"fish/functions" = "~/.config/fish/functions"
"fish/conf.d" = "~/.config/fish/conf.d"

[zsh.files]
"zshenv" = "~/.zshenv"
"zsh/zshrc" = "~/.config/zsh/.zshrc"
"zsh/zplugins" = "~/.config/zsh/zplugins"
"zsh/zalias" = "~/.config/zsh/zalias"

[git.files]
gitconfig = "~/.gitconfig"
gitignore = "~/.gitignore"

[hyprland.files]
hyprland = "~/.config/hypr"
