name: "flake check"
on:
  pull_request:
  push:
jobs:
  flake-check:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          install_url: https://releases.nixos.org/nix/nix-2.25.3/install
          extra_nix_config: |
            experimental-features = nix-command flakes pipe-operators
      - run: nix flake check
