name: "flake check"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: nixbuild/nix-quick-install-action@v29
      - run: nix --extra-experimental-features "pipe-operators" flake check
