name: "flake check"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            /nix/store
      - uses: nixbuild/nix-quick-install-action@v29
        with:
          nix_conf: |
            extra-experimental-features = pipe-operators
      - run: nix flake check
