name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            /nix/store
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake show --json |
          jq  '.packages."x86_64-linux"|keys[]' |
          xargs -I {} nix build .#{}
      - run: nix flake show --json |
          jq  '.nixosConfigurations|keys[]' |
          xargs -I {} nix develop -c nixos-rebuild build --flake .#{}
